spring:
  data:
    mongodb:
      uri: mongodb://ISIS2304B08202320:YTAABuFuBWMw@157.253.236.88:8087/ISIS2304B08202320
      database: ISIS2304B08202320

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
