create sequence hotel_sequence;
CREATE SEQUENCE secuencia
START WITH 1  -- Valor inicial
INCREMENT BY 1;
CREATE SEQUENCE MiSecuencia
START WITH 1  
INCREMENT BY 1;
CREATE SEQUENCE secuenciallegada
START WITH 1  
INCREMENT BY 1;

CREATE TABLE TIPOS_USUARIO
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE), 
    DESCRIPCION VARCHAR2(255 BYTE), 
	CONSTRAINT TIPOS_USUARIO _PK PRIMARY KEY (ID));
    
CREATE TABLE USUARIOS
    (NUM_DOCUMENTO NUMBER,
     TIPO_DOCUMENTO VARCHAR2(255 BYTE),
     NOMBRE VARCHAR2(255 BYTE),
     CORREO VARCHAR2(255 BYTE),
     TIPO_USUARIO NUMBER,
     CONSTRAINT USUARIOS_PK PRIMARY KEY (NUM_DOCUMENTO));
     ALTER TABLE USUARIOS
ADD CONSTRAINT fk_usuarios
    FOREIGN KEY (TIPO_USUARIO)
    REFERENCES TIPOS_USUARIO(ID)
ENABLE;

CREATE TABLE TIPOS_HABITACION
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE), 
    CAPACIDAD NUMBER,
    DOTACION VARCHAR2(255 BYTE), 
	CONSTRAINT TIPOS_HABITACION_PK PRIMARY KEY (ID));


CREATE TABLE HABITACIONES
   (NUMERO NUMBER, 
	TIPO_HABITACION NUMBER,     
	CONSTRAINT HABITACIONES_PK PRIMARY KEY (NUMERO));
ALTER TABLE HABITACIONES
ADD CONSTRAINT fk_habitaciones
    FOREIGN KEY (TIPO_HABITACION)
    REFERENCES TIPOS_HABITACION(ID)
ENABLE;

CREATE TABLE PLAN
(ID NUMBER,
 NOMBRE VARCHAR2(255 BYTE),
 DESCRIPCION VARCHAR2(1000 BYTE),
 CONSTRAINT PLAN_PK PRIMARY KEY (ID)
);

CREATE TABLE RESERVA
(ID_HABITACION NUMBER,
 TITULAR VARCHAR2(255 BYTE),
 PLAN_ELEGIDO VARCHAR2(255 BYTE),
 TARIFA_TOTAL NUMBER(10, 2),
 FECHA_LLEGADA DATE,
 FECHA_SALIDA DATE,
 CONSTRAINT RESERVA_PK PRIMARY KEY(ID_HABITACION));
 
CREATE TABLE LlegadaClientes (
    LlegadaClienteID NUMBER,
    ReservaID NUMBER,
    FechaLlegada DATE,
    CONSTRAINT LLEGADA_PK PRIMARY KEY(LlegadaClienteID));
